In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
label_file_path = r"/content/drive/MyDrive/computer_vision_projects/Expression_Classification_With_Facial_Images/data/label/label.lst"
image_folder_path = r"/content/drive/MyDrive/computer_vision_projects/Expression_Classification_With_Facial_Images/Extracted/origin"

In [ ]:
import pandas as pd
df_info = pd.read_csv(label_file_path, sep=' ', header=None)
col_names = "image_name face_id_in_image face_box_top face_box_left face_box_right face_box_bottom face_box_cofidence expression_label".split(' ')
df_info.columns = col_names
df_info

image_name  face_id_in_image  face_box_top  \
0               angry_actor_104.jpg                 0            28   
1               angry_actor_109.jpg                 0            31   
2               angry_actor_120.jpg                 1            53   
3                angry_actor_13.jpg                 0            77   
4               angry_actor_132.jpg                 0            95   
...                             ...               ...           ...   
91788  surprised_expression_546.jpg                 0            70   
91789  surprised_expression_381.jpg                 0            51   
91790  surprised_expression_395.jpg                 0            27   
91791         ecstatic_asian_31.jpg                 0            60   
91792  surprised_expression_394.jpg                 0            47   

       face_box_left  face_box_right  face_box_bottom  face_box_cofidence  \
0                113             226              141             22.9362   
1                157             345              219             50.3056   
2                 53             372              372             13.9434   
3                 51             362              388             85.8104   
4                 31             412              476             82.3948   
...              ...             ...              ...                 ...   
91788             70             351              351             37.7117   
91789             61             117              107             91.6307   
91790             95             258              190             96.2861   
91791            136             184              108             39.9223   
91792             38             152              161             77.7758   

       expression_label  
0                     0  
1                     0  
2                     2  
3                     3  
4                     0  
...                 ...  
91788                 5  
91789                 5  
91790                 5  
91791                 3  
91792                 5  

[91793 rows x 8 columns]

In [ ]:
for ind in df_info.index:
  df_iterate = df_info['image_name'][ind], df_info['face_box_cofidence'][ind]

print(df_iterate)

('surprised_expression_394.jpg', 77.7758)


In [ ]:
df_sel = df_info[df_info.face_box_cofidence > 60]
df_sel

image_name  face_id_in_image  face_box_top  \
3                  angry_actor_13.jpg                 0            77   
4                 angry_actor_132.jpg                 0            95   
5                 angry_actor_137.jpg                 0            93   
9                 angry_actor_150.jpg                 0            56   
11                 angry_actor_16.jpg                 0           158   
...                               ...               ...           ...   
91786    surprised_expression_409.jpg                 0            80   
91787  expressionless_husband_673.jpg                 0            48   
91789    surprised_expression_381.jpg                 0            51   
91790    surprised_expression_395.jpg                 0            27   
91792    surprised_expression_394.jpg                 0            47   

       face_box_left  face_box_right  face_box_bottom  face_box_cofidence  \
3                 51             362              388             85.8104   
4                 31             412              476             82.3948   
5                468             842              467             88.9519   
9                263             376              169             81.8792   
11               249             521              430             66.4535   
...              ...             ...              ...                 ...   
91786             46             184              218             63.8069   
91787            194             388              242             82.2975   
91789             61             117              107             91.6307   
91790             95             258              190             96.2861   
91792             38             152              161             77.7758   

       expression_label  
3                     3  
4                     0  
5                     0  
9                     0  
11                    0  
...                 ...  
91786                 5  
91787                 4  
91789                 5  
91790                 5  
91792                 5  

[33374 rows x 8 columns]

In [ ]:
for i, row in df_sel.iterrows():
  image_name = row['image_name']
  x1 = row['face_box_left']
  x2 = row['face_box_right']
  y1 = row['face_box_top']
  y2 = row['face_box_bottom']
  a = [x1,x2, y1,y2]

print(row)

image_name            surprised_expression_394.jpg
face_id_in_image                                 0
face_box_top                                    47
face_box_left                                   38
face_box_right                                 152
face_box_bottom                                161
face_box_cofidence                         77.7758
expression_label                                 5
Name: 91792, dtype: object


In [ ]:
import os
import cv2
from tqdm import tqdm_gui

X = []
Y = []

image_directory = '/content/drive/MyDrive/computer_vision_projects/Expression_Classification_With_Facial_Images/Extracted/origin'

for i, row in df_sel.sample(5000).iterrows():
    image_name = row['image_name']
    x1 = row['face_box_left']
    x2 = row['face_box_right']
    y1 = row['face_box_top']
    y2 = row['face_box_bottom']
    label = row['expression_label']

    cropped_path = os.path.join(image_directory, f"cropped_{image_name}")

    # Read the cropped image
    comb_path = os.path.join(image_directory, image_name)
    cropped_image = cv2.imread(comb_path)

    if cropped_image is not None:
        face = cropped_image[x1:x2, y1:y2]

        # Debugging: Print face shape and cropping coordinates
        print(f"Face shape: {face.shape}, x1={x1}, x2={x2}, y1={y1}, y2={y2}")
    else:
        continue

    if face is not None and not face.size == 0:
      face_resized = cv2.resize(face, (64, 64))
    else:
        continue

    X.append(face_resized)
    Y.append(label)

Face shape: (95, 95, 3), x1=295, x2=390, y1=71, y2=166
Face shape: (48, 48, 3), x1=36, x2=84, y1=308, y2=356
Face shape: (114, 114, 3), x1=238, x2=352, y1=47, y2=161
Face shape: (134, 134, 3), x1=269, x2=403, y1=44, y2=178
Face shape: (67, 67, 3), x1=367, x2=434, y1=118, y2=185
Face shape: (134, 134, 3), x1=0, x2=134, y1=33, y2=167
Face shape: (96, 96, 3), x1=1273, x2=1369, y1=672, y2=768
Face shape: (57, 57, 3), x1=299, x2=356, y1=61, y2=118
Face shape: (459, 459, 3), x1=268, x2=727, y1=114, y2=573
Face shape: (79, 79, 3), x1=86, x2=165, y1=33, y2=112
Face shape: (192, 192, 3), x1=464, x2=656, y1=544, y2=736
Face shape: (193, 193, 3), x1=48, x2=241, y1=32, y2=225
Face shape: (96, 96, 3), x1=200, x2=296, y1=56, y2=152
Face shape: (164, 164, 3), x1=82, x2=246, y1=68, y2=232
Face shape: (95, 95, 3), x1=15, x2=110, y1=143, y2=238
Face shape: (0, 96, 3), x1=617, x2=713, y1=152, y2=248
Face shape: (157, 157, 3), x1=26, x2=183, y1=13, y2=170
Face shape: (95, 95, 3), x1=175, x2=270, y1=95, y2

In [ ]:
print(len(X))

In [ ]:
import numpy as np
X = np.array(X)
Y = np.array(Y)

In [ ]:
if isinstance(X, np.ndarray) and isinstance(Y, np.ndarray):
    print("Images are converted to NumPy arrays.")
else:
    print("Images are not converted to NumPy arrays.")


Images are converted to NumPy arrays.


In [ ]:
#X = X/255.0
X_normalized = X.astype('float32') / 255.0

# Check the shape of the array
print("Shape of X_normalized:", X_normalized.shape)

Shape of X_normalized: (789, 64, 64, 3)


In [ ]:
if np.min(X_normalized) >= 0.0 and np.max(X_normalized) <= 1.0:
    print("Images are properly normalized.")
else:
    print("Images are not properly normalized. Pixel value range: [", np.min(X_normalized), ",", np.max(X_normalized), "]")

Images are properly normalized.


In [ ]:
#reshaping images for oversamlping
X_new = X.reshape(-1, 64*64*3)

In [ ]:
# oversampling the images

from imblearn.over_sampling import SMOTE

sampler = SMOTE()

XSMOTE, YSMOTE = sampler.fit_resample(X_new, Y)

In [ ]:
pd.Series(YSMOTE).value_counts()

1    331
3    331
6    331
5    331
4    331
0    331
2    331
dtype: int64

In [ ]:
# again bringing images to its original shape
X = XSMOTE.reshape(-1, 64, 64, 3)

In [ ]:
#  label encoding, OneHotEncoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(Y)
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded.reshape(-1, 1))

# Check the shape of onehot_encoded
print("Shape of onehot_encoded:", onehot_encoded.shape)

Shape of onehot_encoded: (789, 7)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
# Check the first few rows of onehot_encoded
print("First few rows of onehot_encoded:")
print(onehot_encoded[:5])

First few rows of onehot_encoded:
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rescale = 1.0/255,
    rotation_range = 20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True,
    vertical_flip = True
)

datagen.fit(X)

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.optimizers import SGD

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_normalized, onehot_encoded, test_size=0.2, random_state=42)

# Define the batch size and number of epochs
batch_size = 32
epochs = 20

# Build a the CNN model
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.01, momentum=0.9), metrics=['accuracy'])

# Train the model with data augmentation and learning rate scheduling
trained = model.fit(datagen.flow(X_train, y_train, batch_size=batch_size),
                    steps_per_epoch=len(X_train) / batch_size, epochs=epochs, validation_data=(X_test, y_test))

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}")

Epoch 1/50
1562/1562 [==============================] - 146s 93ms/step - loss: 1.6719 - accuracy: 0.3868 - val_loss: 1.4811 - val_accuracy: 0.4745
Epoch 2/50
1562/1562 [==============================] - 132s 84ms/step - loss: 1.3341 - accuracy: 0.5250 - val_loss: 1.2081 - val_accuracy: 0.5797
Epoch 3/50
1562/1562 [==============================] - 140s 89ms/step - loss: 1.2122 - accuracy: 0.5691 - val_loss: 1.0539 - val_accuracy: 0.6265
Epoch 4/50
1562/1562 [==============================] - 140s 90ms/step - loss: 1.1347 - accuracy: 0.5991 - val_loss: 1.0553 - val_accuracy: 0.6415
Epoch 5/50
1562/1562 [==============================] - 137s 88ms/step - loss: 1.0815 - accuracy: 0.6163 - val_loss: 0.9606 - val_accuracy: 0.6667
Epoch 6/50
1562/1562 [==============================] - 136s 87ms/step - loss: 1.0439 - accuracy: 0.6326 - val_loss: 0.9270 - val_accuracy: 0.6802
Epoch 7/50
1562/1562 [==============================] - 139s 89ms/step - loss: 1.0106 - accuracy: 0.6450 - val_loss: 0